export const properties = [
    {
        slug: "torre-a-276m",
        title: "Apartamento 276m² - Torre A",
        description: "A joia da coroa. 4 suítes, living ampliado e vista privilegiada para o clube.",
        price: "Sob Consulta",
        area: 276,
        bedrooms: 4,
        suites: 4,
        bathrooms: 5,
        garages: 3,
        tower: "Torre A",
        images: ["/images/hero-home.png"], // Placeholder re-use
        features: ["Varanda Gourmet Integrada", "Hall Privativo", "Vista Panorâmica", "Dependência de Empregada"],
    },
    {
        slug: "torre-b-215m",
        title: "Apartamento 215m² - Torre B",
        description: "Espaço e conforto para grandes famílias. 4 dormitórios ou 3 suítes com sala ampliada.",
        price: "Sob Consulta",
        area: 215,
        bedrooms: 4,
        suites: 3,
        bathrooms: 4,
        garages: 3,
        tower: "Torre B",
        images: ["/images/hero-home.png"],
        features: ["Varanda Gourmet", "Hall Privativo", "Lavabo", "Despensa"],
    },
    {
        slug: "torre-a-190m",
        title: "Apartamento 190m² - Torre A",
        description: "Planta inteligente com 4 dormitórios e 2 suítes, perfeita para personalizar.",
        price: "Sob Consulta",
        area: 190,
        bedrooms: 4,
        suites: 2,
        bathrooms: 4,
        garages: 2,
        tower: "Torre A",
        images: ["/images/hero-home.png"],
        features: ["Varanda Gourmet", "Cozinha Americana (opcional)", "Lavabo"],
    },
    {
        slug: "torre-b-149m",
        title: "Apartamento 149m² - Torre B",
        description: "O equilíbrio ideal. 3 suítes espaçosas e living integrado.",
        price: "Sob Consulta",
        area: 149,
        bedrooms: 3,
        suites: 3,
        bathrooms: 4,
        garages: 2,
        tower: "Torre B",
        images: ["/images/hero-home.png"],
        features: ["Varanda Gourmet", "Hall Semiprivativo", "Lavabo"],
    },
    {
        slug: "torre-c-133m",
        title: "Apartamento 133m² - Torre C",
        description: "Sofisticação na medida certa. 3 suítes.",
        price: "Sob Consulta",
        area: 133,
        bedrooms: 3,
        suites: 3,
        bathrooms: 4,
        garages: 2,
        tower: "Torre C",
        images: ["/images/hero-home.png"],
        features: ["Varanda com Churrasqueira", "Lavabo"],
    },
    {
        slug: "torre-c-84m",
        title: "Apartamento 84m² - Torre C",
        description: "Compacto de luxo com 2 suítes. Ideal para investir ou começar a vida a dois.",
        price: "Sob Consulta",
        area: 84,
        bedrooms: 2,
        suites: 2,
        bathrooms: 3,
        garages: 1,
        tower: "Torre C",
        images: ["/images/hero-home.png"],
        features: ["Varanda Integrada", "Lavabo"],
    },
];
